version: "3.7"
services:

#====================== ELASTIC SEARCH ======================
# Master node
  elasticsearch-master:
    image: elasticsearch:8.9.0
    container_name: es1-master
    restart: always
    environment:
      - xpack.security.enabled=false
    ulimits: 
      memlock:
        soft: -1 
        hard: -1
    volumes:
      - ./elasticsearch-master-volume:/usr/share/elasticsearch/data
      - ./elastic-cluster/master.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200" # web-interface
      - "9300:9300" # connection between cluster nodes
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
        - elk 
    logging:
      options:
        max-size: "100m"
        max-file: "5"
# Data node
  elasticsearch-data:
    image: elasticsearch:8.9.0
    container_name: es1-data
    restart: always
    environment:
      - xpack.security.enabled=false
    ulimits: 
      memlock:
        soft: -1 
        hard: -1
    volumes:
      - ./elasticsearch-data-volume:/usr/share/elasticsearch/data
      - ./elastic-cluster/data.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9201:9200" # web-interface
      - "9301:9300" # connection between cluster nodes
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
        - elk 
    logging:
      options:
        max-size: "100m"
        max-file: "5"

# Open DevTools in Kibana and check status of nodes with command: GET /_cat/nodes?v
# Common information about nodes http://192.168.1.200:9200/_nodes/stats
# Common information about cluster http://192.168.1.200:9200/_cluster/stats

#====================== KIBANA ======================
  kibana:
    container_name: kibana
    image: kibana:8.9.0
    restart: always
    environment:
      SERVER_NAME: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
        - elk 
    depends_on:
      - elasticsearch-master

#====================== LOGSTASH ======================
#=====logstash 1
  logstash:
    image: logstash:8.9.0
    container_name: logstash1
    ports:
     - "5044:5044"
     - "9600:9600"
     - "12201:12201/udp"
    volumes:
      - ./stash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./stash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - elk
    depends_on:
      - elasticsearch-master
#=====logstash 2
  logstash2:
    image: logstash:8.9.0
    container_name: logstash2
    ports:
     - "12202:12201/udp"
    volumes:
      - ./stash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./stash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - elk
    depends_on:
      - elasticsearch-master
#=====logstash 3
  logstash3:
    image: logstash:8.9.0
    container_name: logstash3
    ports:
     - "12203:12201/udp"
    volumes:
      - ./stash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./stash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - elk
    depends_on:
      - elasticsearch-master
  
networks:
  elk:
    driver: bridge
